# Generated by Django 4.1 on 2022-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_date_created_producto_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='producto/%y/%m/%d', verbose_name='Imagen'),
        ),
    ]
