# Generated by Django 4.1 on 2022-09-30 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_alter_usuario_identificacion_alter_usuario_telefono'),
        ('facturacion', '0004_delete_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.vehículo', verbose_name='VehÍculo'),
        ),
    ]
