# Generated by Django 4.1 on 2022-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_remove_vehículo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='identificacion',
            field=models.CharField(blank=True, max_length=11, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=13, unique=True, verbose_name='Número de celular'),
        ),
    ]
